export const ADD_THUMB = "ADD-THUMB"
export const THUMB_POSITION_CHANGE = "THUMB-POSITION-CHANGE"
export const SET_SLIDER_SCALE_SIZE_PX = "SET-SLIDER-SCALE-SIZE-PX"
export  const SET_SLIDER_SCALE_SIZE_NUMBER = "SET-SLIDER-SCALE-SIZE-NUMBER"